ALTER TYPE "RelationshipType" ADD VALUE IF NOT EXISTS 'SON';
ALTER TYPE "RelationshipType" ADD VALUE IF NOT EXISTS 'DAUGHTER';
ALTER TYPE "RelationshipType" ADD VALUE IF NOT EXISTS 'STEP_SON';
ALTER TYPE "RelationshipType" ADD VALUE IF NOT EXISTS 'STEP_DAUGHTER';

ALTER TABLE "JoinRequest" ADD COLUMN IF NOT EXISTS "gender" TEXT;
